language: python
python:
  - "2.7"
  - "3.6"
  
# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install h5py --only-binary=h5py
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install .

# Command to run test
script: 
    - python setup.py test
    
branches:
  only:
    - master
