name: Test Dockerfile

on:
  push:
    paths-ignore:
      - '**.ipynb'
      - '**.png'
      - '**.rst'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.ipynb'
      - '**.png'
      - '**.rst'
      - '**.md'

jobs:
  build-cpu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker CPU image
        run: docker build . --file Dockerfile --tag turboseti-docker:$(date +%s)

  build-gpu:

    runs-on: nvidia-gpu

        steps:
      - uses: actions/checkout@v2
      - name: Build the Docker GPU image
        run: docker build --build-arg IMAGE=cupy/cupy:v8.6.0 --file Dockerfile --tag turboseti-docker-gpu:$(date +%s) .
      - name: Test turbo_seti with GPU
        uses: docker://turboseti-docker-gpu
        run: nvidia-smi 
