name: Push to Docker Hub

on:
  push:
    paths-ignore:
      - '**.rst'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ucberkeleyseti/turbo_seti
          tags: latest

